format = """
$hostname\
$os\
$custom$directory\
[\uE0B0](fg:bar_two bg:bar_three)\
$git_branch\
$git_status\
[\uE0B0](fg:bar_three bg:bar_four)\
$c\
$dart\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$lua\
$nodejs\
$nim\
$php\
$python\
$rlang\
$ruby\
$rust\
$scala\
$conda\
[\uE0B0](fg:bar_four)\
$linebreak
$character
"""

# remove the "[❯ ](text_five)" if you want prompt on the same line as the bar...

right_format = """
$cmd_duration
"""
# cut from after "$os\"...
# [\uE0B0](fg:bar_one bg:bar_two)\

add_newline = true

palette = 'theme_cat'

# Defines the colour palette for the theme
[palettes.theme]
bar_one = '#24415C'
bar_two = '#0C4F68'
bar_three = '#394260'
bar_four = '#212736'
bar_five = '#1D2230'
text_one = '#090C0C'
text_two = '#EEEEEE'
text_three = '#a6adc8'

# use this instead
[palettes.theme_cat]
bar_one = '##b4befe'
# bar_two = '#89b4fa'
# bar_two = "#fab387"
# bar_two = '#94e2d5'
# bar_two = '#cba6f7'
# bar_two = '#b4befe'
# bar_two = '#7f849c'
# bar_two = "#181825"
# bar_two = "#11111b"
bar_two = "#1e1e2e"
bar_three = "#1e1e2e"
bar_four = "#1e1e2e"
# bar_three = '#394260'
# bar_four = '#212736'
bar_five = '#1D2230'
text_one = '#090C0C'
# text_two = '#181825'
text_two = '#89b4fa'
# text_two = "#cba6f7"
# text_two = "#cdd6f4"
text_three = "#b4befe"
# text_three = '#a6adc8'
text_four = '#f38ba8'
text_five = '#94e2d5'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[character]
success_symbol = "[❯](text_five)"
error_symbol = "[❯](text_four)"

[os]
style = 'bg:bar_one fg:text_one'
format = '[ $symbol ]($style)'
disabled = true

# [username]
# style = 'bold fg:text_two bg:bar_two'
# format = '[ james@ ]($style)'
# disabled = false

[hostname]
style = 'fg:text_two bg:bar_two'
format = '[ \[james@xps17\] ]($style)'
disabled = false

[os.symbols]
Alpine = ''
Amazon = ''
Android = ''
Arch = ''
CentOS = ''
Debian = ''
DragonFly = ''
Emscripten = ''
EndeavourOS = ''
# 
Fedora = ''
FreeBSD = ''
Garuda = '﯑'
Gentoo = ''
HardenedBSD = 'ﲊ'
Illumos = ''
Linux = "\uE712"
Macos = "\uE711"
Manjaro = ''
Mariner = ''
MidnightBSD = ''
Mint = ''
NetBSD = ''
NixOS = ''
OpenBSD = ''
openSUSE = ''
OracleLinux = ''
Pop = ''
Raspbian = ''
Redhat = "\uE7BB"
RedHatEnterprise = "\uE7BB"
Redox = ''
Solus = 'ﴱ'
SUSE = ''
Ubuntu = ''
Unknown = ''
Windows = ''

[directory]
truncation_length = 0
truncation_symbol = '.../'
truncate_to_repo = false
fish_style_pwd_dir_length = 1
style = 'bold fg:text_two bg:bar_two'
format = '[ $path ]($style)'

[custom.home]
when = ''' test '$HOME' = '$PWD' '''
style = 'bold fg:text_two bg:bar_two'
symbol = ' '

[custom.folder]
when = ''' test '$HOME' != '$PWD' '''
style = 'bold fg:text_two bg:bar_two'
symbol = ''

[directory.substitutions]
'Documents' = '  '
'Dropbox' = '  '
'Downloads' = '  '
'Music' = '  '
'Pictures' = '  '

[git_branch]
symbol = ''
style = 'fg:text_three bg:bar_three'
format = '[ $symbol $branch ]($style)'

[git_status]
style = 'bold fg:text_four bg:bar_three'
format = '[$all_status$ahead_behind ]($style)'

[c]
symbol = ' '
style = 'fg:text_three bg:bar_four'
format = '[ $symbol ($version) ]($style)'

[conda]
symbol = '🅒 '
style = 'fg:text_five bg:bar_four'
format = '[ $symbol $environment ]($style)'
truncation_length = 1
ignore_base = false
disabled = false

[dart]
symbol = ' '
style = 'fg:text_three bg:bar_four'
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = ' '
style = 'fg:text_three bg:bar_four'
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = ' '
style = 'fg:text_three bg:bar_four'
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = ' '
style = 'fg:text_three bg:bar_four'
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = ' '
style = 'fg:text_three bg:bar_four'
format = '[ $symbol ($version) ]($style)'

[java]
symbol = ' '
style = 'fg:text_three bg:bar_four'
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = ' '
style = 'fg:text_three bg:bar_four'
format = '[ $symbol ($version) ]($style)'

[lua]
symbol = ' '
style = 'fg:text_three bg:bar_four'
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ' '
style = 'fg:text_three bg:bar_four'
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = ' '
style = 'fg:text_three bg:bar_four'
format = '[ $symbol ($version) ]($style)'

[php]
symbol = ' '
style = 'fg:text_three bg:bar_four'
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ''
style = 'fg:text_three bg:bar_four'
format = '[ $symbol ($version) (${virtualenv} )]($style)'

[rlang]
symbol = 'R '
style = 'fg:text_three bg:bar_four'
format = '[ $symbol($version) ]($style)'

[ruby]
symbol = ' '
style = 'fg:text_three bg:bar_four'
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ' '
style = 'fg:text_three bg:bar_four'
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = ' '
style = 'fg:text_three bg:bar_four'
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = '%R'                   # Hour:Minute Format
style = 'fg:text_three bg:bar_three'
format = '[   $time ]($style)'

[cmd_duration]
disabled = false
min_time = 20
show_milliseconds = true
format = '[   $duration ](italic gray)'
show_notifications = false
