return {
	"nvim-treesitter/nvim-treesitter",
	-- event = "BufRead *",
	-- lazy = false,
	event = "VeryLazy",
	build = ":TSUpdate",
	dependencies = {
		"nvim-treesitter/nvim-treesitter-textobjects",
	},
	cmd = { "TSUpdate", "TSUpdateSync", "TSInstall" },
	keys = {
		{ "<leader>h", "<cmd>TSEnable highlight<cr>", desc = "Treesitter enable highlight", mode = "n" },
	},
	config = function()
		require("nvim-ts-autotag").setup()
	end,
	opts_extend = { "ensure_installed" },
	opts = {
		sync_install = true,
		highlight = { enable = true },
		indent = { enable = true },
		ensure_installed = {
			"awk",
			"bash",
			"bibtex",
			"c",
			"css",
			"diff",
			"go",
			"html",
			"javascript",
			"jsdoc",
			"json",
			"jsonc",
			"julia",
			"latex",
			"lua",
			"luadoc",
			"luap",
			"markdown",
			"markdown_inline",
			"ninja",
			"printf",
			"python",
			"query",
			"r",
			"regex",
			"ron",
			"rst",
			"rust",
			"toml",
			"tsx",
			"typescript",
			"vim",
			"vimdoc",
			"xml",
			"yaml",
		},
		incremental_selection = {
			enable = true,
			keymaps = {
				init_selection = "<C-space>",
				node_incremental = "<C-space>",
				scope_incremental = false,
				node_decremental = "<bs>",
			},
		},
		extobjects = {
			move = {
				enable = true,
				goto_next_start = { ["]f"] = "@function.outer", ["]c"] = "@class.outer" },
				goto_next_end = { ["]F"] = "@function.outer", ["]C"] = "@class.outer" },
				goto_previous_start = { ["[f"] = "@function.outer", ["[c"] = "@class.outer" },
				goto_previous_end = { ["[F"] = "@function.outer", ["[C"] = "@class.outer" },
			},
		},
	},
}
